// Isolated integration tests. Uses the built Worker and a temporary D1 database.
// Synthetic identities are injected only into this local test runtime.
import {createRequire} from 'node:module';
import {readdirSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const root=resolve('dist/server');
const files=['index.js',...readdirSync(root,{recursive:true}).filter(p=>p.endsWith('.js')&&p!=='index.js')];
const mf=new Miniflare({modules:files.map(p=>({type:'ESModule',path:resolve(root,p)})),modulesRoot:root,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{PLATFORM_ADMIN_USER_IDS:'qa-admin'},cf:false});
let checks=0;
function check(condition,message){assert.ok(condition,message);checks++;console.log('PASS',message)}
async function call(path,{user,body,token,headers={}}={}){const h={...headers,...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{}),...(body?{'content-type':'application/json',origin:'https://randevu.test'}:{}),...(token?{authorization:'Bearer '+token}:{})};const r=await mf.dispatchFetch('https://randevu.test/api/v1/'+path,{method:body?'POST':'GET',headers:h,...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Non-JSON '+r.status+' '+text.slice(0,300))}return {status:r.status,data}}
const day=(n)=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
try{
 const db=await mf.getD1Database('DB');
 for(const file of readdirSync('drizzle').filter(p=>p.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();
 check((await call('workspace')).status===401,'Anonymous workspace access is denied');
 const A=(await call('businesses',{user:'qa-a',body:{name:'Test Studio A',slug:'test-a',category:'Kuaför & Berber',city:'İstanbul'}})).data.id;
 const B=(await call('businesses',{user:'qa-b',body:{name:'Test Studio B',slug:'test-b',category:'Kuaför & Berber',city:'Ankara'}})).data.id;
 check(!!A&&!!B&&A!==B,'Two independent businesses can be created');
 const types=(await call('business-types')).data.businessTypes;
 check(types.length===10&&types.some(x=>x.category==='Psikolog'&&x.config.businessProfile.customerLabel==='Danışan'),'Business type catalog exposes sector-specific terminology');
 check((await call('workspace?tenant='+A,{user:'qa-a'})).data.configuration.businessType==='hair_salon','Workspace includes its resolved business configuration');
 check((await call('workspace?tenant='+B,{user:'qa-a'})).status===403,'Business A cannot read business B');
 check((await call('services',{user:'qa-a',body:{tenant_id:B,name:'Foreign Service',duration:30,price:10000}})).status===403,'Business A cannot write services into business B');
 check((await call('public/test-a')).status===404,'Unapproved business is not publicly bookable');
 check((await call('admin',{user:'qa-a'})).status===403,'Business owner has no platform administrator privileges');
 await call('admin',{user:'qa-admin',body:{action:'business-status',id:A,status:'approved'}});
 const hours=Object.fromEntries([0,1,2,3,4,5,6].map(k=>[k,[540,1080]]));
 for(const [tenant_id,user] of [[A,'qa-a'],[B,'qa-b']]){
  await call('settings',{user,body:{tenant_id,name:'Test Studio '+user,category:'Kuaför & Berber',city:'Test',address:'Test',phone:'',description:'',hours,cancellation_hours:2}});
  await call('services',{user,body:{tenant_id,name:'Saç kesimi',duration:45,price:65000}});
  await call('staff',{user,body:{tenant_id,name:'Test Uzman',title:'Uzman',hours}});
 }
 const wa=(await call('workspace?tenant='+A,{user:'qa-a'})).data,wb=(await call('workspace?tenant='+B,{user:'qa-b'})).data;
 check(wa.services.length===1&&wb.services.length===1&&wa.services[0].id!==wb.services[0].id,'Service lists stay scoped to their business');
 check((await call('services',{user:'qa-a',body:{tenant_id:A,name:'Invalid duration',duration:17,price:10000}})).status===400,'Non-aligned service durations are rejected');
 const S=wa.services[0].id,P=wa.staff[0].id,date=day(3);
 const book={slug:'test-a',service_id:S,staff_id:P,date,minute:600,name:'Test Müşteri',phone:'05550001234',email:'test@example.test',consent:false};
 check((await call(`availability?slug=test-a&service=${S}&date=${date}&staff=${P}`)).data.slots.some(s=>s.minute===600),'Public customer sees actual availability without an account');
 const concurrent=await Promise.all([call('bookings',{body:book}),call('bookings',{body:{...book,name:'İkinci Müşteri',phone:'05550005678'}})]);
 check(concurrent.filter(r=>r.status===201).length===1&&concurrent.filter(r=>r.status===409).length===1,'Concurrent bookings cannot reserve the same staff time twice');
 const booked=concurrent.find(r=>r.status===201).data;
 check(booked.price===65000,'Price is read from the server service record');
 check((await call('manage',{token:booked.token})).data.appointment.id===booked.id,'Private management token opens only its own appointment');
 check((await call('manage',{token:'a'.repeat(64)})).status===404,'Unknown management tokens cannot read appointments');
 check((await call('appointment',{user:'qa-b',body:{tenant_id:B,id:booked.id,status:'cancelled'}})).status===404,'Other business cannot cancel the appointment by guessing its ID');
 check((await call('bookings',{body:{...book,staff_id:wb.staff[0].id}})).status===409,'Foreign staff cannot be used to create an appointment');
 check((await call('appointment',{user:'qa-a',body:{tenant_id:A,id:booked.id,status:'completed'}})).status===400,'Future appointments cannot be marked completed');
 check((await call('closures',{user:'qa-a',body:{tenant_id:A,staff_id:P,date,reason:'Test izin'}})).status===409,'Leave cannot silently displace existing appointments');
 check((await call('manage',{token:booked.token,body:{action:'review',rating:5,comment:'Test değerlendirme'}})).status===400,'Reviews require a completed appointment');
 check((await call('manage',{token:booked.token,body:{action:'reschedule',date,minute:720,staff_id:P}})).status===200,'Guest can reschedule using the private management link');
 const availability=(await call(`availability?slug=test-a&service=${S}&date=${date}&staff=${P}`)).data.slots;
 check(availability.some(s=>s.minute===600)&&!availability.some(s=>s.minute===720),'Rescheduling atomically releases old time and reserves new time');
 check((await call('manage',{token:booked.token,body:{status:'cancelled'}})).status===200,'Guest can cancel within the cancellation window');
 check((await call(`availability?slug=test-a&service=${S}&date=${date}&staff=${P}`)).data.slots.some(s=>s.minute===720),'Cancelled appointment time becomes available again');
 const wafter=(await call('workspace?tenant='+A,{user:'qa-a'})).data;
 check(wafter.customers.length===1&&wafter.appointments.length===1,'Failed booking transaction leaves no orphan customer or appointment');
 const pendingPnL=(await call('branches?tenant='+A+'&month='+date.slice(0,7),{user:'qa-a'})).data;
 check(pendingPnL.summary.revenue===0,'Customer creation and an uncompleted appointment do not create manual revenue');
 check((await call('closures',{user:'qa-a',body:{tenant_id:A,staff_id:P,date,reason:'Test izin'}})).status===200,'Free staff day can be marked as leave');
 check((await call(`availability?slug=test-a&service=${S}&date=${date}&staff=${P}`)).data.slots.length===0,'Leave excludes the staff member from availability');
 const raceDate=day(6);
 const leaveRace=await Promise.all([call('bookings',{body:{...book,date:raceDate}}),call('closures',{user:'qa-a',body:{tenant_id:A,staff_id:P,date:raceDate,reason:'Concurrent leave'}})]);
 check(leaveRace.filter(r=>r.status===409).length===1&&leaveRace.filter(r=>r.status===200||r.status===201).length===1,'Concurrent leave and booking cannot both succeed');
 let fkRejected=false;try{await db.prepare('UPDATE appointments SET service_id=? WHERE id=?').bind(wb.services[0].id,booked.id).run()}catch{fkRejected=true}
 check(fkRejected,'Database foreign keys reject cross-business service relations');
 const second=(await call('bookings',{body:{...book,date:day(4)}})).data;
 check(!!second.id,'Customer can book another open day');
 const past=day(-1);
 await db.prepare('UPDATE appointments SET date=?,minute=540 WHERE id=?').bind(past,second.id).run();
 await db.prepare('DELETE FROM slots WHERE appointment_id=?').bind(second.id).run();
 check((await call('appointment',{user:'qa-a',body:{tenant_id:A,id:second.id,status:'completed'}})).status===200,'Ended appointment can be completed by its owner');
 const completedPnL=(await call('branches?tenant='+A+'&month='+past.slice(0,7),{user:'qa-a'})).data;
 check(completedPnL.summary.revenue===65000&&completedPnL.branches.find(b=>b.is_primary===1)?.completed===1,'Completed service price automatically contributes to branch revenue and profit calculation');
 check((await call('manage',{token:second.token,body:{action:'review',rating:5,comment:'İyi bir deneyimdi.'}})).status===200,'Completed appointment accepts one customer review');
 check((await call('manage',{token:second.token,body:{action:'review',rating:5,comment:'Tekrar değerlendirme'}})).status===409,'Duplicate review is rejected');
 check((await call('public/test-a')).data.reviews.length===0,'Unmoderated reviews are not public');
 const admin=(await call('admin',{user:'qa-admin'})).data;
 await call('admin',{user:'qa-admin',body:{action:'review-status',id:admin.reviews[0].id,status:'published'}});
 check((await call('public/test-a')).data.reviews.length===1,'Only approved reviews become public');
 check((await call('manage',{token:second.token,body:{action:'complaint',message:'Bu bir test şikâyetidir.'}})).status===200,'Customer can file a complaint using the management link');
 const result=(await call('workspace?tenant='+A,{user:'qa-a'})).data;
 check(result.customers[0].visits===1&&result.customers[0].total_spent===65000,'Customer history aggregates completed visits and spend');
 const aresult=await call('assistant',{body:{slug:'test-a',message:day(5)+' öğleden sonra saç kesimi'}});
 check(aresult.data.slots.length>0&&aresult.data.slots.every(s=>s.minute>=720),'Turkish assistant returns available afternoon slots');
 // Membership ownership is independent of contact information and account preference.
 check((await call('account')).data.authenticated===false,'Anonymous account status exposes no profile');
 check((await call('my-bookings')).status===401,'Anonymous users cannot read member appointment history');
 check((await call('my-bookings',{user:'qa-c1'})).status===409,'Authenticated user completes a profile before opening member history');
 const profile={name:'Üye Bir',phone:'05550001234',city:'İstanbul',account_type:'customer',marketing_consent:false};
 check((await call('account',{body:profile})).status===401,'Profile creation requires a verified session');
 const signup=await call('account',{user:'qa-c1',body:{...profile,user_id:'qa-admin',email:'spoof@example.test',disabled:0,isAdmin:true}});
 check(signup.status===200&&signup.data.profile.user_id==='qa-c1'&&signup.data.profile.email==='qa-c1@example.test'&&!signup.data.isAdmin,'Profile identity and email come from the trusted session, not the submitted form');
 check((await call('account',{user:'qa-c2',body:{...profile,account_type:'admin'}})).status===400,'Self-assigned administrator account type is rejected');
 await call('account',{user:'qa-c2',body:{...profile,name:'Üye İki',account_type:'business'}});
 check((await call('workspace?tenant='+A,{user:'qa-c2'})).status===403,'Business account preference does not grant access to any business');
 check((await call('admin',{user:'qa-c2'})).status===403,'Business account preference never grants administrator rights');
 await call('account',{user:'qa-c1',body:{...profile,user_id:'qa-c2',city:'İzmir'}});
 check((await call('account',{user:'qa-c2'})).data.profile.city==='İstanbul','Profile updates cannot target another member');
 check((await call('my-bookings',{user:'qa-c1'})).data.appointments.length===0,'Matching a customer phone never imports their historical appointments');
 check((await call('favorites',{user:'qa-c1',body:{tenant_id:A,saved:true,user_id:'qa-c2'}})).status===200,'Member can save an approved business to their own favorites');
 check((await call('favorites',{user:'qa-c1'})).data.favorites.length===1&&(await call('favorites',{user:'qa-c2'})).data.favorites.length===0,'Favorites are private to the member');
 check((await call('favorites',{user:'qa-c1',body:{tenant_id:B,saved:true}})).status===404,'Unapproved business cannot be saved as a bookable favorite');
 const memberBooking=(await call('bookings',{user:'qa-c1',body:{...book,date:day(8),user_id:'qa-c2'}})).data;
 check(memberBooking.saved_to_account===true,'New public booking is atomically connected to the signed-in member');
 const owned=(await call('my-bookings',{user:'qa-c1'})).data.appointments;
 check(owned.length===1&&owned[0].id===memberBooking.id&&!JSON.stringify(owned).includes(memberBooking.token)&&!('token_hash' in owned[0]),'Member history returns only owned appointments and contains no management secrets');
 check((await call('my-appointment?id='+memberBooking.id,{user:'qa-c2'})).status===404,'Another member cannot read an appointment by its ID');
 check((await call('my-appointment',{user:'qa-c2',body:{id:memberBooking.id,status:'cancelled'}})).status===404,'Another member cannot cancel an appointment by its ID');
 check((await call('claim-booking',{user:'qa-c2',body:{token:memberBooking.token}})).status===409,'A private token cannot transfer an already linked appointment to a different account');
 check((await call('claim-booking',{user:'qa-c2',body:{token:'invalid'}})).status===400&&(await call('claim-booking',{user:'qa-c2',body:{token:'b'.repeat(64)}})).status===404,'Malformed or unknown management proof cannot claim an appointment');
 check((await call('my-appointment',{user:'qa-c1',body:{id:memberBooking.id,action:'reschedule',date:day(8),minute:720,staff_id:P}})).status===200,'Member can reschedule their own booking without a private token');
 check((await call('my-appointment',{user:'qa-c1',body:{id:memberBooking.id,action:'review',rating:5,comment:'Erken değerlendirme'}})).status===400,'Membership cannot bypass the completed-visit review rule');
 check((await call('claim-booking',{user:'qa-c1',body:{token:booked.token}})).status===200,'Member can explicitly link an older guest booking using its private token');
 check((await call('my-bookings',{user:'qa-c1'})).data.appointments.length===2,'Claiming one booking does not claim other bookings with the same phone');
 const unclaimed=(await call('bookings',{body:{...book,date:day(10)}})).data;
 const claims=await Promise.all([call('claim-booking',{user:'qa-c1',body:{token:unclaimed.token}}),call('claim-booking',{user:'qa-c2',body:{token:unclaimed.token}})]);
 check(claims.filter(r=>r.status===200).length===1&&claims.filter(r=>r.status===409).length===1,'Concurrent claims preserve exactly one account owner');
 await call('account',{user:'qa-a',body:{...profile,name:'İşletme sahibi',account_type:'business'}});
 const manual=(await call('bookings',{user:'qa-a',body:{...book,tenant_id:A,date:day(9),phone:'05559991234'}})).data;
 check(manual.id&&!manual.saved_to_account&&(await call('my-bookings',{user:'qa-a'})).data.appointments.length===0,'Manual business booking is not mistaken for the owner’s personal appointment');
 const before=(await call('account',{user:'qa-c1'})).data.businesses.length;
 const invalidSetup=await call('businesses',{user:'qa-c1',body:{name:'Kurulum Testi',slug:'invalid-setup',category:'Kuaför & Berber',starter:{service_name:'Test',duration:17,price:10000,staff_name:'Test Uzman',staff_title:'Uzman',hours}}});
 check(invalidSetup.status===400&&(await call('account',{user:'qa-c1'})).data.businesses.length===before,'Invalid initial service leaves no half-created business');
 const setup=await call('businesses',{user:'qa-c1',body:{name:'Kurulum Testi',slug:'setup-test',category:'Kuaför & Berber',city:'İzmir',phone:'05551112233',address:'Test adresi',starter:{service_name:'İlk hizmet',duration:30,price:50000,staff_name:'İlk Personel',staff_title:'Uzman',hours}}});
 const created=(await call('workspace?tenant='+setup.data.id,{user:'qa-c1'})).data;
 check(setup.status===201&&created.services.length===1&&created.staff.length===1&&created.business.status==='pending','Business wizard creates business, owner, first service, staff and hours atomically');
 check((await call('workspace?tenant='+setup.data.id,{user:'qa-c2'})).status===403,'Wizard-created business remains isolated from other members');
 check((await call('account',{user:'qa-c1',body:profile,headers:{origin:'https://evil.example','sec-fetch-site':'cross-site'}})).status===403,'Cross-site profile mutation is denied');
 const soon=(await call('bookings',{user:'qa-c1',body:{...book,date:day(1)}})).data;
 await db.prepare('UPDATE businesses SET cancellation_hours=72 WHERE id=?').bind(A).run();
 check((await call('my-appointment',{user:'qa-c1',body:{id:soon.id,status:'cancelled'}})).status===400,'Account management enforces the same cancellation deadline as guest links');
 await db.prepare('UPDATE businesses SET cancellation_hours=2 WHERE id=?').bind(A).run();
 check((await call('admin',{user:'qa-admin',body:{action:'user-status',id:'qa-c2',disabled:true}})).status===200,'Administrator can suspend a customer membership without business ownership');
 check((await call('account',{user:'qa-c2'})).status===403&&(await call('account',{user:'qa-c2',body:profile})).status===403,'Suspended member cannot read or reactivate their own profile');
 await call('admin',{user:'qa-admin',body:{action:'user-status',id:'qa-c2',disabled:false}});
 check((await call('account',{user:'qa-c2'})).status===200,'Administrator can restore a suspended membership');
 const memberAdmin=(await call('admin',{user:'qa-admin'})).data;
 check(memberAdmin.users.some(u=>u.user_id==='qa-c2'&&u.account_type==='business'),'Administrator directory includes members with no business');
 check((await call('admin',{user:'qa-admin',body:{action:'user-status',id:'qa-b',disabled:true}})).status===200,'Administrator can disable another business user');
 check((await call(`availability?tenant=${B}&service=${wb.services[0].id}&date=${date}`,{user:'qa-b'})).status===403,'Disabled business user cannot access business data');
 await call('admin',{user:'qa-admin',body:{action:'business-status',id:A,status:'deleted'}});
 check((await call('public/test-a')).status===404,'Deleted business disappears from public booking');
 check((await call('workspace?tenant='+A,{user:'qa-b'})).status===403,'Business access remains independently scoped');
 console.log(JSON.stringify({passed:checks,failed:0}));
}finally{await mf.dispose()}
