import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {tenant,user,admin,all,one,q,db,now,uid,ApiError} from './server';
import {today,addDays} from './types';
import {requirePlanModule,tenantPlan,PLAN_LIMITS} from './entitlements';
const cfg=()=>env as any;
export const defaultGrowth={theme:'auto',hide_brand:0,autopilot:0,recall_days:30,welcome:'Merhaba! Randevu almak istediğiniz hizmeti ve günü yazabilirsiniz.'};
export async function hasPremium(id:string){const s=await one("SELECT 1 n FROM recurring_subscriptions WHERE tenant_id=? AND test_mode=0 AND plan IN ('pro','plus') AND paid_until>?",id,now());return !!s;}
export async function publicStyle(id:string){const g=await one('SELECT theme,hide_brand FROM growth_settings WHERE tenant_id=?',id);return {theme:g?.theme||'auto',hide_brand:!!g?.hide_brand&&await hasPremium(id)}}
export async function recallCandidates(id:string,days:number){return all(`SELECT c.id,c.name,c.phone,MAX(a.date) last_visit FROM customers c JOIN appointments a ON a.tenant_id=c.tenant_id AND a.customer_id=c.id WHERE c.tenant_id=? AND c.consent=1 AND a.status='completed' AND NOT EXISTS(SELECT 1 FROM appointments f WHERE f.tenant_id=c.tenant_id AND f.customer_id=c.id AND f.status='confirmed' AND f.date>=?) GROUP BY c.id HAVING MAX(a.date)<=? ORDER BY last_visit LIMIT 100`,id,today(),addDays(today(),-days));}
export async function growthSnapshot(id:string){await requirePlanModule(id,'growth');const b=await tenant(id),g=await one('SELECT * FROM growth_settings WHERE tenant_id=?',id)||defaultGrowth;const plan=await tenantPlan(id);return {settings:g,premium:await hasPremium(id),referral_enabled:cfg().REFERRAL_PROGRAM_ENABLED==='true'&&PLAN_LIMITS.plus.modules.referral,referral_allowed:PLAN_LIMITS[plan].modules.referral,referral_reward:50000,referrals:await all('SELECT status,reward,created_at FROM referrals WHERE referrer_tenant=? ORDER BY created_at DESC LIMIT 100',id),balance:(await one('SELECT COALESCE(SUM(amount),0) balance FROM credit_ledger WHERE tenant_id=?',id)).balance,ledger:await all('SELECT amount,kind,description,created_at FROM credit_ledger WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100',id),candidates:await recallCandidates(id,g.recall_days),recalls:await all('SELECT status,created_at FROM recall_jobs WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100',id),booking_path:'/'+b.slug,public_site:cfg().PUBLIC_SITE_READY==='true'};}
export async function saveGrowth(id:string,input:any){await requirePlanModule(id,'growth');const x=z.object({theme:z.enum(['auto','salon','consulting','fitness']),hide_brand:z.boolean(),autopilot:z.boolean(),recall_days:z.number().int().min(7).max(365),welcome:z.string().trim().min(10).max(500)}).parse(input);if(x.hide_brand&&!await hasPremium(id))throw new ApiError('Marka gizlemek için aktif Pro veya Plus aboneliği gerekir.',402);if(x.autopilot){const {waConnection}=await import('./whatsapp');const c=waConnection(id);if(!c||!c.recall_template||cfg().RECALL_SCHEDULER_READY!=='true'||cfg().PUBLIC_SITE_READY!=='true')throw new ApiError('Önce WhatsApp numarası, onaylı mesaj şablonu ve günlük otomasyon bağlantısı tamamlanmalı.',409)}await q('INSERT INTO growth_settings(tenant_id,theme,hide_brand,autopilot,recall_days,welcome,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(tenant_id) DO UPDATE SET theme=excluded.theme,hide_brand=excluded.hide_brand,autopilot=excluded.autopilot,recall_days=excluded.recall_days,welcome=excluded.welcome,updated_at=excluded.updated_at',id,x.theme,+x.hide_brand,+x.autopilot,x.recall_days,x.welcome,now()).run();return {ok:true}}
export async function referralOperation(newId:string,owner:string,slug:unknown){if(typeof slug!=='string'||!/^[a-z][a-z0-9-]{2,59}$/.test(slug))return null;const b=await one("SELECT id FROM businesses WHERE slug=? AND status='approved' AND demo=0 AND NOT EXISTS(SELECT 1 FROM members WHERE tenant_id=businesses.id AND user_id=?)",slug,owner);if(!b)return null;// Neta ortaklığı yalnızca Plus paketteki işletmelere kredi kazandırır.
 const plan=await tenantPlan(b.id);if(!PLAN_LIMITS[plan].modules.referral)return null;return q("INSERT INTO referrals(referred_tenant,referrer_tenant,owner_id,status,reward,created_at) VALUES(?,?,?,'pending',50000,?) ON CONFLICT DO NOTHING",newId,b.id,owner,now());}
export async function approveReferral(id:string){if(cfg().REFERRAL_PROGRAM_ENABLED!=='true')return;await db().batch([q(`INSERT INTO credit_ledger(id,tenant_id,amount,kind,reference,description,created_at) SELECT ?,r.referrer_tenant,r.reward,'referral','referral:'||r.referred_tenant,'Onaylanan işletme daveti',? FROM referrals r JOIN businesses b ON b.id=r.referred_tenant JOIN businesses f ON f.id=r.referrer_tenant WHERE r.referred_tenant=? AND r.status='pending' AND b.status='approved' AND b.demo=0 AND f.status='approved' AND EXISTS(SELECT 1 FROM services WHERE tenant_id=b.id AND active=1) AND EXISTS(SELECT 1 FROM staff WHERE tenant_id=b.id AND active=1) ON CONFLICT(reference) DO NOTHING`,uid(),now(),id),q("UPDATE referrals SET status='earned' WHERE referred_tenant=? AND EXISTS(SELECT 1 FROM credit_ledger WHERE reference='referral:'||?)",id,id)]);}
export async function platformGrowth(){await admin();return {referrals:await all('SELECT r.*,b.name referred_name,f.name referrer_name FROM referrals r JOIN businesses b ON b.id=r.referred_tenant JOIN businesses f ON f.id=r.referrer_tenant ORDER BY r.created_at DESC LIMIT 100'),enabled:cfg().REFERRAL_PROGRAM_ENABLED==='true'};}
export async function referralReview(input:any){const u=await admin(),x=z.object({id:z.string().min(1)}).parse(input);await approveReferral(x.id);await q('INSERT INTO audit VALUES(?,?,?,?,?)',uid(),u.userId,'referral.review',x.id,now()).run();return {ok:true}}
