export const HELP_ARTICLES=[
{id:'link',title:'Randevu linkimi nasıl paylaşırım?',keywords:'link bağlantı paylaş instagram qr',view:'share',body:'Panelin üstündeki Randevu linkim düğmesini açın. Bağlantıyı kopyalayabilir veya WhatsApp’ta paylaşabilirsiniz. Müşteriniz hizmeti, ücreti, personeli ve uygun saati seçerek üye olmadan randevu alır. İşletme onayı ve sitenin dış erişimi tamamlanmış olmalıdır.'},
{id:'debt',title:'Veresiye ve kısmi tahsilat nasıl çalışır?',keywords:'borç veresiye tahsilat ödeme alacak',view:'receivables',body:'Borç / Veresiye bölümünde müşteri ve ödenmemiş tutarı girin. Müşteriden para aldığınızda Tahsilat kaydet düğmesini kullanın. Kısmi ödeme mümkündür; kalan tutar hesaplanır. Yanlış tahsilatı gerekçesiyle geri alabilirsiniz. Neta bu ekrandan para transferi yapmaz.'},
{id:'journey',title:'Hizmet yolculuğunu müşterim görebilir mi?',keywords:'yolculuk süreç aşama seans paket',view:'journeys',body:'Hizmet yolculuğu bölümünde müşteri, süreç adı ve aşamalarını belirleyin. Sıradaki aşamayı tamamlayın veya süreci duraklatın. Müşteriyle paylaş düğmesi yalnızca aşamaları gösteren özel bir bağlantı üretir. Paylaşımı kapatabilirsiniz. Yeni link eski linki geçersiz kılar.'},
{id:'wa',title:'WhatsApp’tan alınan randevu takvime düşer mi?',keywords:'whatsapp bot otomasyon ortak takvim',view:'whatsapp',body:'Evet, Meta Cloud API bağlantısı tamamlandığında müşteri WhatsApp üzerinden hizmet ve gün sorar, sunulan saati seçer, adını yazar ve ONAYLA diyerek randevu oluşturur. Web ve WhatsApp aynı takvimi kullanır. Saat son onayda dolmuşsa müşteri yeni saat seçmeye yönlendirilir. Bağlantı yokken mesaj gönderilmez.'},
{id:'recall',title:'Müşterileri otomatik geri çağırabilir miyim?',keywords:'pazarlama geri kazanma otopilot çağırma kampanya',view:'growth',body:'Pazarlama ve büyüme bölümünden son tamamlanan hizmetten kaç gün sonra geri çağırma yapılacağını belirleyin. Yalnızca iletişim izni olan, yeni randevusu bulunmayan müşteriler listelenir. Gönderim için WhatsApp bağlantısı, onaylı mesaj şablonu ve günlük zamanlayıcı gerekir. DUR yanıtı geri çağırma iznini kapatır.'},
{id:'referral',title:'Referans kredisi ve marka gizleme nedir?',keywords:'referans kredi cüzdan davet logo marka',view:'growth',body:'Referans bağlantınızla katılan farklı bir işletme, kurulumu ve platform onayı tamamlandıktan sonra kampanya açıksa bir defa 500 TL Neta kredisi kazandırır. Bu nakit çekilebilir bir bakiye değildir. Hareketleri Pazarlama ve büyüme bölümünde görünür. Müşteri sayfasında Neta markasını gizleme, aktif Pro veya Plus aboneliği gerektirir.'},
{id:'subscription',title:'Abonelik ödemesi kime gider?',keywords:'abonelik iyzico paytr banka kart fiyat pro plus',view:'billing',body:'İşletme Neta yazılım aboneliğini ödeme kuruluşunun formunda öder. Kart bilgileri ödeme kuruluşuna girilir. Otomatik abonelik, sağlayıcının aylık ödeme planıyla yürür; yenilemeyi abonelik ekranından iptal edebilirsiniz. Neta işletmenin müşterilerinden aldığı hizmet ücretlerine aracılık etmez. Sağlayıcı bağlantısı ve satış koşulları hazır değilse tahsilat açılmaz.'},
{id:'availability',title:'Saatler neden görünmüyor?',keywords:'müsait saat izin çalışma personel kapalı',view:'staff',body:'İşletme ve personelin çalışma saatlerini, izin günlerini ve hizmet süresini kontrol edin. Randevu, iki çalışma aralığının kesişimine sığmalıdır. Dolu saatler sunulmaz. Randevu başlangıcı en az 5 dakika ileride olmalı; en çok 90 gün sonrası seçilebilir.'},
{id:'demand',title:'Kaçan gelir kesin bir kayıp mı?',keywords:'kaçan gelir talep ghost fırsat analiz',view:'demand',body:'Talep fırsatları, uygun saat bulunamayan aramaları ve hizmet fiyatlarından hesaplanan potansiyeli gösterir. Bu tutar gerçekleşmiş veya garanti edilmiş gelir değildir. Ek saat veya personel kararını arama dağılımı ve mevcut kapasiteyle birlikte değerlendirin.'},
{id:'theme',title:'Sektörüme uygun sayfayı nasıl seçerim?',keywords:'sektör tema tasarım kuaför diyetisyen spor danışman',view:'growth',body:'Pazarlama ve büyüme bölümünde Otomatik, Salon, Danışmanlık veya Spor şablonunu seçin. Otomatik şablon işletme kategorisine göre seçilir. Fiyatlar ve müsaitlik aynı hizmet ve takvim kayıtlarından gelir. İşletmenin müşteri ödemeleri kendi ödeme kanallarında kalır.'}
];
export function helpMatches(message:string){const words=message.toLocaleLowerCase('tr-TR').split(/\W+/u).filter(w=>w.length>2);return HELP_ARTICLES.map(a=>({...a,score:words.filter(w=>(a.title+' '+a.keywords).toLocaleLowerCase('tr-TR').includes(w)).length})).sort((a,b)=>b.score-a.score).filter(a=>a.score>0).slice(0,3)}
