import {z} from 'zod';
import {all,one,q,db,tenant,user,uid,now,name,date,hash,secret,ApiError} from './server';
import {requirePlanModule} from './entitlements';
export const JOURNEY_TEMPLATES={care:['İlk görüşme','Hizmet planı','Uygulama / seans','Takip görüşmesi'],coaching:['Tanışma ve hedefler','Programın hazırlanması','İlk kontrol','İlerleme görüşmesi','Program değerlendirmesi'],consulting:['İhtiyaç görüşmesi','Planlama','Çalışma süreci','Son değerlendirme'],custom:['Başlangıç','Uygulama','Tamamlandı']};
export async function journeySnapshot(id:string){await tenant(id);await requirePlanModule(id,'journeys');return {journeys:await all('SELECT j.id,j.tenant_id,j.customer_id,j.title,j.template,j.status,j.version,j.shared,j.created_at,j.updated_at,c.name customer_name FROM journeys j JOIN customers c ON c.tenant_id=j.tenant_id AND c.id=j.customer_id WHERE j.tenant_id=? ORDER BY j.created_at DESC LIMIT 500',id),steps:await all('SELECT s.* FROM journey_steps s JOIN (SELECT id FROM journeys WHERE tenant_id=? ORDER BY created_at DESC LIMIT 500) j ON j.id=s.journey_id WHERE s.tenant_id=? ORDER BY s.position',id,id),templates:JOURNEY_TEMPLATES}}
export async function createJourney(id:string,input:any){await requirePlanModule(id,'journeys');const u=await user(),x=z.object({customer_id:z.string(),title:name,template:z.enum(['care','coaching','consulting','custom']),steps:z.array(z.object({title:name,due_date:date.nullable().optional()})).min(2).max(12)}).parse(input);if(!await one('SELECT id FROM customers WHERE tenant_id=? AND id=?',id,x.customer_id))throw new ApiError('Müşteri bulunamadı.',404);const jid=uid(),stamp=now();await db().batch([q('INSERT INTO journeys(id,tenant_id,customer_id,title,template,share_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',jid,id,x.customer_id,x.title,x.template,await hash(secret()),stamp,stamp),...x.steps.map((s,i)=>q('INSERT INTO journey_steps(id,tenant_id,journey_id,position,title,due_date) VALUES(?,?,?,?,?,?)',uid(),id,jid,i,s.title,s.due_date||null)),q('INSERT INTO audit VALUES(?,?,?,?,?)',uid(),u.userId,'journey.create',jid,stamp)]);return {id:jid}}
export async function changeJourney(id:string,input:any){await requirePlanModule(id,'journeys');const u=await user(),x=z.object({id:z.string(),version:z.number().int(),action:z.enum(['advance','pause','resume','cancel','share','unshare'])}).parse(input),j=await one('SELECT * FROM journeys WHERE tenant_id=? AND id=?',id,x.id);if(!j)throw new ApiError('Hizmet yolculuğu bulunamadı.',404);if(j.version!==x.version)throw new ApiError('Kayıt değişti. Listeyi yenileyin.',409);const stamp=now(),ops=[q('INSERT INTO journey_mutations VALUES(?,?,?)',id,j.id,j.version+1)],token=x.action==='share'?secret():null;let status=j.status;
 if(x.action==='advance'){if(j.status!=='active')throw new ApiError('Önce süreci devam ettirin.',409);const steps=await all('SELECT * FROM journey_steps WHERE tenant_id=? AND journey_id=? AND completed_at IS NULL ORDER BY position',id,j.id);if(!steps.length)throw new ApiError('Tüm aşamalar tamamlandı.',409);ops.push(q('UPDATE journey_steps SET completed_at=? WHERE tenant_id=? AND id=?',stamp,id,steps[0].id));if(steps.length===1)status='completed';}
 if(x.action==='pause'){if(j.status!=='active')throw new ApiError('Bu süreç duraklatılamaz.',409);status='paused'}
 if(x.action==='resume'){if(j.status!=='paused')throw new ApiError('Bu süreç devam ettirilemez.',409);status='active'}
 if(x.action==='cancel')status='cancelled';
 if(token)ops.push(q('UPDATE journeys SET share_hash=?,shared=1 WHERE tenant_id=? AND id=?',await hash(token),id,j.id));
 if(x.action==='unshare')ops.push(q('UPDATE journeys SET shared=0,share_hash=? WHERE tenant_id=? AND id=?',await hash(secret()),id,j.id));
 ops.push(q('UPDATE journeys SET status=?,version=version+1,updated_at=? WHERE tenant_id=? AND id=?',status,stamp,id,j.id),q('INSERT INTO audit VALUES(?,?,?,?,?)',uid(),u.userId,'journey.'+x.action,j.id,stamp));await db().batch(ops);return {ok:true,token}}
export async function sharedJourney(token:string){if(!/^[a-f0-9]{64}$/.test(token))throw new ApiError('Bağlantı geçerli değil.',404);const j=await one("SELECT j.id,j.tenant_id,j.title,j.status,b.name business_name FROM journeys j JOIN businesses b ON b.id=j.tenant_id WHERE j.share_hash=? AND j.shared=1 AND b.status NOT IN ('suspended','deleted')",await hash(token));if(!j)throw new ApiError('Bağlantı kapatılmış veya yenilenmiş.',404);return {title:j.title,status:j.status,business_name:j.business_name,steps:await all('SELECT title,position,due_date,completed_at FROM journey_steps WHERE tenant_id=? AND journey_id=? ORDER BY position',j.tenant_id,j.id)}}
