import {z} from 'zod';
import {all,one,q,db,tenant,user,uid,now,name,phone,date,ApiError} from './server';
import {today} from './types';
import {requirePlanModule} from './entitlements';
const minor=z.number().int().min(1).max(100000000);
export async function contact(id:string,input:any){await tenant(id);const x=z.object({name,phone,email:z.string().email().or(z.literal('')).default('')}).parse(input);await q('INSERT INTO customers(id,tenant_id,name,phone,email,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(tenant_id,phone) DO NOTHING',uid(),id,x.name,x.phone,x.email,now()).run();return await one('SELECT id,name,phone FROM customers WHERE tenant_id=? AND phone=?',id,x.phone)}
export async function receivableSnapshot(id:string){await tenant(id);await requirePlanModule(id,'receivables');const debts=await all('SELECT r.*,c.name customer_name,c.phone customer_phone FROM receivables r JOIN customers c ON c.tenant_id=r.tenant_id AND c.id=r.customer_id WHERE r.tenant_id=? ORDER BY r.created_at DESC LIMIT 1000',id);return {debts,totals:await one("SELECT COALESCE(SUM(CASE WHEN status='open' THEN remaining ELSE 0 END),0) remaining,COALESCE(SUM(CASE WHEN status='open' AND due_date<? THEN remaining ELSE 0 END),0) overdue,COUNT(DISTINCT CASE WHEN status='open' AND remaining>0 THEN customer_id END) customers FROM receivables WHERE tenant_id=?",today(),id),payments:await all('SELECT p.*,r.title,c.name customer_name FROM receivable_payments p JOIN receivables r ON r.tenant_id=p.tenant_id AND r.id=p.receivable_id JOIN customers c ON c.tenant_id=r.tenant_id AND c.id=r.customer_id WHERE p.tenant_id=? ORDER BY p.created_at DESC LIMIT 1000',id)}}
export async function createReceivable(id:string,input:any){await requirePlanModule(id,'receivables');const u=await user(),x=z.object({customer_id:z.string().min(1),appointment_id:z.string().nullable().optional(),title:name,amount:minor,due_date:date.nullable().optional(),note:z.string().trim().max(300).default(''),idempotency_key:z.string().uuid()}).parse(input);if(!await one('SELECT id FROM customers WHERE tenant_id=? AND id=?',id,x.customer_id))throw new ApiError('Müşteri bulunamadı.',404);if(x.appointment_id&&!await one("SELECT id FROM appointments WHERE tenant_id=? AND id=? AND customer_id=? AND status!='cancelled'",id,x.appointment_id,x.customer_id))throw new ApiError('Randevu bu müşteriye ait değil.',400);const prior=await one('SELECT id FROM receivables WHERE tenant_id=? AND idempotency_key=?',id,x.idempotency_key);if(prior)return prior;const rid=uid();await db().batch([q('INSERT INTO receivables(id,tenant_id,customer_id,appointment_id,title,amount,remaining,due_date,note,created_by,created_at,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',rid,id,x.customer_id,x.appointment_id||null,x.title,x.amount,x.amount,x.due_date||null,x.note,u.userId,now(),x.idempotency_key),q('INSERT INTO audit VALUES(?,?,?,?,?)',uid(),u.userId,'receivable.create',rid,now())]);return {id:rid}}
export async function recordCollection(id:string,input:any){await requirePlanModule(id,'receivables');const u=await user(),x=z.object({receivable_id:z.string().min(1),amount:minor,method:z.enum(['cash','bank','card','other']),note:z.string().trim().max(300).default(''),idempotency_key:z.string().uuid()}).parse(input);const r=await one('SELECT * FROM receivables WHERE tenant_id=? AND id=?',id,x.receivable_id);if(!r)throw new ApiError('Borç kaydı bulunamadı.',404);const prior=await one('SELECT id FROM receivable_payments WHERE tenant_id=? AND idempotency_key=?',id,x.idempotency_key);if(prior)return prior;if(r.status!=='open'||x.amount>r.remaining)throw new ApiError('Tahsilat kalan borcu aşamaz.',409);const pid=uid();await db().batch([q('INSERT INTO receivable_payments(id,tenant_id,receivable_id,amount,method,note,created_by,created_at,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?)',pid,id,r.id,x.amount,x.method,x.note,u.userId,now(),x.idempotency_key),q('INSERT INTO audit VALUES(?,?,?,?,?)',uid(),u.userId,'receivable.collection',pid,now())]);return {id:pid}}
export async function reviseReceivable(id:string,input:any){await requirePlanModule(id,'receivables');const u=await user(),x=z.object({action:z.enum(['reverse-payment','void']),id:z.string().min(1),reason:z.string().trim().min(3).max(200)}).parse(input);if(x.action==='reverse-payment'){const p=await one('SELECT id,status FROM receivable_payments WHERE tenant_id=? AND id=?',id,x.id);if(!p)throw new ApiError('Tahsilat kaydı bulunamadı.',404);await db().batch([q("UPDATE receivable_payments SET status='reversed',reversal_reason=?,reversed_at=? WHERE tenant_id=? AND id=? AND status='recorded'",x.reason,now(),id,x.id),q('INSERT INTO audit VALUES(?,?,?,?,?)',uid(),u.userId,'receivable.reverse',x.id,now())]);}else{const r=await one('SELECT * FROM receivables WHERE tenant_id=? AND id=?',id,x.id);if(!r)throw new ApiError('Borç kaydı bulunamadı.',404);if(r.remaining!==r.amount)throw new ApiError('Önce bu kayda bağlı tahsilatları düzeltin.',409);const result=await q("UPDATE receivables SET status='void',note=note||? WHERE tenant_id=? AND id=? AND remaining=amount AND status='open'",'\nİptal gerekçesi: '+x.reason,id,x.id).run();if(result.meta.changes)await q('INSERT INTO audit VALUES(?,?,?,?,?)',uid(),u.userId,'receivable.void',x.id,now()).run()}return {ok:true}}
