import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {all,one,q,db,user,tenant,admin,isAdmin,uid,now,ApiError,hash} from './server';
import {appOrigin} from './identity';
import {hmacHex,utf8Base64,equalSecret} from './security';
const cfg=()=>env as any;
const ref=z.string().regex(/^[a-zA-Z0-9_-]{8,120}$/);
const planSchema=z.object({code:z.enum(['normal','pro','plus']),name:z.string().min(2).max(60),amount:z.number().int().min(100).max(100000000),reference:ref});
export function recurringPlans(){try{const p=z.array(planSchema).max(3).parse(JSON.parse(cfg().NETA_PLANS_JSON||'[]'));if(new Set(p.map(v=>v.code)).size!==p.length)return [];return p}catch{return []}}
export function recurringConnection(){return {provider:'iyzico',configured:!!(cfg().IYZICO_API_KEY&&cfg().IYZICO_SECRET_KEY&&cfg().IYZICO_MERCHANT_ID&&recurringPlans().length),live:cfg().IYZICO_LIVE==='true',public_site:cfg().PUBLIC_SITE_READY==='true',enabled:cfg().RECURRING_SALES_ENABLED==='true',seller_ready:!!(cfg().NETA_SELLER_NAME&&cfg().NETA_SELLER_ADDRESS&&cfg().NETA_SUPPORT_EMAIL&&/^https:\/\//.test(cfg().NETA_SUBSCRIPTION_TERMS_URL||''))};}
async function iyzico(path:string,payload?:any){const c=cfg();if(!c.IYZICO_API_KEY||!c.IYZICO_SECRET_KEY)throw new ApiError('Abonelik sağlayıcısı bağlanmadı.',503);const random=uid(),raw=payload?JSON.stringify(payload):'',signature=await hmacHex(random+path+raw,c.IYZICO_SECRET_KEY),authorization='IYZWSv2 '+utf8Base64('apiKey:'+c.IYZICO_API_KEY+'&randomKey:'+random+'&signature:'+signature);const response=await fetch((c.IYZICO_LIVE==='true'?'https://api.iyzipay.com':'https://sandbox-api.iyzipay.com')+path,{method:payload?'POST':'GET',headers:{Authorization:authorization,'x-iyzi-rnd':random,'Content-Type':'application/json'},...(payload?{body:raw}:{}),redirect:'manual',signal:AbortSignal.timeout(20000)});if(!response.ok)throw new ApiError('Ödeme sağlayıcısına ulaşılamadı.',503);const result:any=await response.json();if(result.status!=='success')throw new ApiError('Ödeme sağlayıcısı işlemi tamamlayamadı. Sağlayıcı panelindeki durumu kontrol edin.',502);return result;}
export async function recurringSnapshot(id:string){await tenant(id);const c=recurringConnection(),u=await user();return {connection:c,plans:recurringPlans().map(({reference,...p})=>p),subscription:await one('SELECT plan,amount,state,test_mode,paid_until,created_at,updated_at FROM recurring_subscriptions WHERE tenant_id=?',id),payments:await all('SELECT reference,amount,period_start,period_end,test_mode,created_at FROM recurring_events WHERE tenant_id=? ORDER BY period_end DESC LIMIT 100',id),available:!!(c.configured&&c.public_site&&c.enabled&&c.seller_ready&&appOrigin()&&(c.live||await isAdmin(u))),seller:{name:cfg().NETA_SELLER_NAME||'',email:cfg().NETA_SUPPORT_EMAIL||'',address:cfg().NETA_SELLER_ADDRESS||'',terms_url:cfg().NETA_SUBSCRIPTION_TERMS_URL||''}};}
export async function beginRecurring(id:string,input:any){const b=await tenant(id),u=await user(),x=z.object({plan:z.enum(['normal','pro','plus']),terms_accepted:z.literal(true),name:z.string().trim().min(2).max(80),surname:z.string().trim().min(2).max(80),identity:z.string().regex(/^\d{10,11}$/),city:z.string().trim().min(2).max(80)}).parse(input),c=recurringConnection(),plan=recurringPlans().find(p=>p.code===x.plan);if(!c.configured||!c.enabled||!c.public_site||!c.seller_ready||!appOrigin()||!plan)throw new ApiError('Aylık abonelik satışa açılmadı.',503);if(!c.live&&!await isAdmin(u))throw new ApiError('Sağlayıcı test aşamasında.',403);
 const buyer=await one('SELECT * FROM billing_profiles WHERE tenant_id=?',b.id);if(!buyer)throw new ApiError('Önce fatura iletişim bilgilerinizi kaydedin.',409);
 // Match the server-owned catalog against the provider. No client can set price or interval.
 const verified=(await iyzico('/v2/subscription/pricing-plans/'+encodeURIComponent(plan.reference))).data;
 if(!verified||Math.round(Number(verified.price)*100)!==plan.amount||verified.currencyCode!=='TRY'||verified.paymentInterval!=='MONTHLY'||Number(verified.paymentIntervalCount||1)!==1||Number(verified.trialPeriodDays||0)!==0||Number(verified.recurrenceCount||0)!==0)throw new ApiError('Sağlayıcıdaki aylık plan ile Neta fiyatı uyuşmuyor.',409);
 const prev=await one('SELECT * FROM recurring_subscriptions WHERE tenant_id=?',id);if(prev&&!['CANCELED','EXPIRED','failed'].includes(prev.state))throw new ApiError('Devam eden bir abonelik veya ödeme işlemi var. Durumu yenileyin; yeni ödeme açılmadı.',409);
 const requestId=uid(),stamp=now();await db().batch([q("INSERT INTO recurring_subscriptions(tenant_id,plan_reference,plan,amount,request_id,test_mode,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(tenant_id) DO UPDATE SET reference=NULL,customer_reference=NULL,token_hash=NULL,plan_reference=excluded.plan_reference,plan=excluded.plan,amount=excluded.amount,request_id=excluded.request_id,test_mode=excluded.test_mode,state='creating',created_at=excluded.created_at,updated_at=excluded.updated_at WHERE recurring_subscriptions.state IN ('CANCELED','EXPIRED','failed')",id,plan.reference,plan.code,plan.amount,requestId,c.live?0:1,stamp,stamp),q('INSERT INTO audit VALUES(?,?,?,?,?)',uid(),u.userId,'subscription.terms.accepted:'+plan.code,id,stamp)]);
 const claim=await one('SELECT request_id FROM recurring_subscriptions WHERE tenant_id=?',id);if(claim.request_id!==requestId)throw new ApiError('Başka bir abonelik işlemi başladı.',409);
 try{const result=await iyzico('/v2/subscription/checkoutform/initialize',{locale:'tr',conversationId:requestId,callbackUrl:appOrigin()+'/api/integrations/iyzico/callback',pricingPlanReferenceCode:plan.reference,subscriptionInitialStatus:'ACTIVE',customer:{name:x.name,surname:x.surname,email:buyer.email,gsmNumber:buyer.phone,identityNumber:x.identity,billingAddress:{address:buyer.address,contactName:x.name+' '+x.surname,city:x.city,country:'Turkey'}}});if(typeof result.token!=='string'||result.token.length>300||typeof result.checkoutFormContent!=='string'||result.checkoutFormContent.length>100000)throw new Error('INVALID_CHECKOUT');await q("UPDATE recurring_subscriptions SET token_hash=?,state='checkout',updated_at=? WHERE tenant_id=? AND request_id=?",await hash(result.token),now(),id,requestId).run();return {form:result.checkoutFormContent,test_mode:!c.live,amount:plan.amount};}catch(e){await q("UPDATE recurring_subscriptions SET state='review',updated_at=? WHERE tenant_id=? AND request_id=?",now(),id,requestId).run();throw new ApiError('Ödeme sayfası hazırlanamadı. Çift tahsilatı önlemek için işlem incelemeye alındı; sağlayıcıdan kontrol edilmelidir.',503)}
}
async function syncSubscription(row:any){if(!row.reference)return;const result=await iyzico('/v2/subscription/subscriptions/'+encodeURIComponent(row.reference));const d=result.data?.items?.find((v:any)=>v.referenceCode===row.reference)||result.data;if(!d||d.referenceCode!==row.reference||d.pricingPlanReferenceCode!==row.plan_reference||d.customerReferenceCode!==row.customer_reference)throw new ApiError('ABONELIK_ESLESMEDI',409);const state=z.enum(['ACTIVE','PENDING','UNPAID','UPGRADED','CANCELED','EXPIRED']).parse(d.subscriptionStatus),ops:any[]=[];
 for(const o of d.orders||[]){if(o.orderStatus!=='SUCCESS')continue;if(o.currencyCode!=='TRY'||Math.round(Number(o.price)*100)!==row.amount)throw new ApiError('ODEME_TUTARI_ESLESMEDI',409);const start=new Date(o.startPeriod),end=new Date(o.endPeriod);if(!Number.isFinite(+start)||!Number.isFinite(+end)||+end<=+start||+end-+start>32*86400000)throw new ApiError('ODEME_DONEMI_ESLESMEDI',409);ops.push(q('INSERT INTO recurring_events(reference,tenant_id,amount,period_start,period_end,test_mode,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT DO NOTHING',ref.parse(o.referenceCode),row.tenant_id,row.amount,start.toISOString(),end.toISOString(),row.test_mode,now()));}
 ops.push(q('UPDATE recurring_subscriptions SET state=?,paid_until=(SELECT MAX(period_end) FROM recurring_events WHERE tenant_id=? AND test_mode=?),updated_at=? WHERE tenant_id=? AND reference=?',state,row.tenant_id,row.test_mode,now(),row.tenant_id,row.reference),q("INSERT INTO subscriptions(tenant_id,paid_until,updated_at) SELECT ?,MAX(period_end),? FROM recurring_events WHERE tenant_id=? AND test_mode=0 HAVING MAX(period_end) IS NOT NULL ON CONFLICT(tenant_id) DO UPDATE SET paid_until=MAX(subscriptions.paid_until,excluded.paid_until),updated_at=excluded.updated_at",row.tenant_id,now(),row.tenant_id));await db().batch(ops);
}
export async function recurringCallback(req:Request){const raw=await req.text();if(raw.length>8000)throw new ApiError('INVALID_BODY',413);const ps=new URLSearchParams(raw);if(ps.getAll('token').length!==1)throw new ApiError('INVALID_TOKEN');const token=ps.get('token')||'';if(token.length>300)throw new ApiError('INVALID_TOKEN');const row=await one('SELECT * FROM recurring_subscriptions WHERE token_hash=?',await hash(token));if(!row)throw new ApiError('UNKNOWN_PAYMENT',404);const result=await iyzico('/v2/subscription/checkoutform/'+encodeURIComponent(token)),d=result.data;if(!d||d.pricingPlanReferenceCode!==row.plan_reference||!d.referenceCode||!d.customerReferenceCode||result.conversationId&&result.conversationId!==row.request_id)throw new ApiError('PAYMENT_MISMATCH',409);await q('UPDATE recurring_subscriptions SET reference=?,customer_reference=?,updated_at=? WHERE tenant_id=? AND token_hash=?',ref.parse(d.referenceCode),ref.parse(d.customerReferenceCode),now(),row.tenant_id,row.token_hash).run();await syncSubscription({...row,reference:d.referenceCode,customer_reference:d.customerReferenceCode});return new Response(null,{status:303,headers:{Location:appOrigin()+'/abonelik?tenant='+encodeURIComponent(row.tenant_id),'Cache-Control':'no-store','Referrer-Policy':'no-referrer'}})}
export async function recurringWebhook(req:Request){const c=cfg();if(!c.IYZICO_SECRET_KEY||!c.IYZICO_MERCHANT_ID)throw new ApiError('NOT_CONFIGURED',503);const raw=await req.text();if(raw.length>16000)throw new ApiError('TOO_LARGE',413);const x=z.object({iyziEventType:z.enum(['subscription.order.success','subscription.order.failure']),subscriptionReferenceCode:ref,orderReferenceCode:ref,customerReferenceCode:ref}).parse(JSON.parse(raw));const sig=await hmacHex(c.IYZICO_MERCHANT_ID+c.IYZICO_SECRET_KEY+x.iyziEventType+x.subscriptionReferenceCode+x.orderReferenceCode+x.customerReferenceCode,c.IYZICO_SECRET_KEY);if(!equalSecret((req.headers.get('x-iyz-signature-v3')||'').toLowerCase(),sig))throw new ApiError('INVALID_SIGNATURE',403);const row=await one('SELECT * FROM recurring_subscriptions WHERE reference=? AND customer_reference=?',x.subscriptionReferenceCode,x.customerReferenceCode);if(!row)throw new ApiError('SUBSCRIPTION_PENDING_RECONCILIATION',409);await syncSubscription(row);return new Response('OK');}
export async function recurringAction(id:string,input:any){await tenant(id);const x=z.object({action:z.enum(['refresh','cancel']),confirmed:z.boolean().optional()}).parse(input),row=await one('SELECT * FROM recurring_subscriptions WHERE tenant_id=?',id);if(!row?.reference)throw new ApiError('Sağlayıcıya bağlı abonelik bulunamadı.',409);if(x.action==='cancel'){if(!x.confirmed)throw new ApiError('İptal onayı gerekiyor.');await iyzico('/v2/subscription/subscriptions/'+encodeURIComponent(row.reference)+'/cancel',{});await q("UPDATE recurring_subscriptions SET state='CANCELED',updated_at=? WHERE tenant_id=?",now(),id).run()}else await syncSubscription(row);return {ok:true}}
export async function platformRecurring(){await admin();return {connection:recurringConnection(),plans:recurringPlans().map(({reference,...p})=>p),subscriptions:await all('SELECT s.tenant_id,s.plan,s.amount,s.state,s.test_mode,s.paid_until,b.name business_name FROM recurring_subscriptions s JOIN businesses b ON b.id=s.tenant_id ORDER BY s.updated_at DESC LIMIT 200'),totals:await one('SELECT COALESCE(SUM(amount),0) amount,COUNT(*) payments FROM recurring_events WHERE test_mode=0')};}
