'use client';
import {Scissors,ShieldCheck,Dumbbell,MapPin,Phone,Sparkles,Link2} from 'lucide-react';
import {Avatar} from '@/components/product/common';
export function selectTheme(category:string,choice='auto'){if(choice!=='auto')return choice;return /spor|fitness|ders/i.test(category)?'fitness':/klinik|danış|diyet|psikolog/i.test(category)?'consulting':'salon'}
export default function BookingTheme({data,onAssistant,children,favorite}:any){
 const b=data.business,site=data.website,theme=selectTheme(b.category,data.presentation?.theme),content={salon:{Icon:Scissors,label:'SİZİN TARZINIZ. SİZİN ZAMANINIZ.',title:'Bir sonraki randevunuz.',hint:'Hizmetinizi ve uzmanınızı seçin; fiyatı en baştan görün.'},consulting:{Icon:ShieldCheck,label:'GÖRÜŞMENİZE YER AÇIN',title:'Size uygun bir görüşme.',hint:'Görüşme türü, süresi ve ücreti açık. Sağlık bilgisi paylaşmadan randevunuzu planlayın.'},fitness:{Icon:Dumbbell,label:'PROGRAMINIZA ZAMAN AYIRIN',title:'Sıradaki dersinizi planlayın.',hint:'Dersinizi ve eğitmeninizi seçin; uygun zamanları görün.'}}[theme as 'salon'|'consulting'|'fitness']!;
 const label=site?.eyebrow||content.label,title=site?.hero_title||content.title,hint=site?.hero_text||content.hint,phone=site?.contact_phone||b.phone;
 return <main className={'booking-page sector-booking sector-'+theme}>
  <aside className="business-profile"><div className="sector-profile-top"><content.Icon size={32}/><span className="eyebrow">{b.category}</span></div><div className="business-profile-body"><div className="business-name-row"><h1>{b.name}</h1>{favorite}</div><p>{b.description||hint}</p>{site?.about_text&&<p>{site.about_text}</p>}<div className="profile-detail"><MapPin size={17}/><span>{b.address||b.city||'Konum eklenmedi'}</span></div>{phone&&<div className="profile-detail"><Phone size={17}/><span>{phone}</span></div>}{site?.instagram_url&&<a className="profile-detail" href={site.instagram_url} target="_blank" rel="noopener noreferrer"><Link2 size={17}/><span>Instagram</span></a>}<div className="sector-assurance"><ShieldCheck size={18}/><span>Üyelik zorunlu değil<br/><small>Ücret ve süre rezervasyondan önce görünür.</small></span></div><div className="profile-team"><h3>{theme==='fitness'?'Eğitmenleriniz':theme==='consulting'?'Görüşeceğiniz uzman':'Uzmanlarımız'}</h3><div className="team-avatars">{data.staff.map((p:any)=><div key={p.id}><Avatar name={p.name} color={p.color} large/><small>{p.name}</small></div>)}</div></div><button className="button full" onClick={onAssistant}><Sparkles size={17}/>Uygun saat sor</button>{site?.show_reviews!==false&&(data.reviews||[]).slice(0,3).map((r:any,i:number)=><div className="review" key={i}><span>{'★'.repeat(r.rating)}</span><p>{r.comment}</p></div>)}</div></aside>
  <section className="panel booking-form-panel"><span className="eyebrow">{label}</span><h2>{title}</h2><p className="muted">{hint}</p>{children}</section>
 </main>
}
