'use client';
import {useEffect,useState,useCallback} from 'react';
import {ArrowLeft,ArrowRight,Check,CreditCard,ExternalLink,Landmark,LockKeyhole,RefreshCw,ShieldCheck,Store,Wallet} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {api,Brand,ThemeToggle,Field,Pick,Busy} from './common';
import {AccountGate,AccountMenu,useSession} from './session';
import {money} from '@/lib/types';

import {RecurringPlans,PlatformRecurring} from './recurring';
const statuses:Record<string,string>={creating:'Hazırlanıyor',pending:'Doğrulama bekleniyor',paid:'Tahsil edildi',test_paid:'Test tamamlandı',failed:'Tamamlanamadı'};
const dates=(v:string)=>new Date(v).toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'});
function Header(){return <header className="public-header"><Brand/><nav><a className="text-button" href="/panel"><ArrowLeft size={15}/>İşletme paneli</a><ThemeToggle/><AccountMenu/></nav></header>}
export default function BillingPage({platform=false}:{platform?:boolean}){return <><Header/><main className="billing-page"><AccountGate returnTo={platform?'/yonetim/odemeler':'/abonelik'}>{platform?<PlatformBilling/>:<BusinessBilling/>}</AccountGate></main></>}
function History({orders,platform=false}:{orders:any[];platform?:boolean}){return <section className="panel billing-history"><div className="panel-header"><h2>{platform?'Platform tahsilatları':'Ödeme geçmişi'}</h2><span className="billing-state">{orders.length} işlem</span></div>{!orders.length?<div className="billing-empty"><Wallet size={28}/><h3>Henüz ödeme işlemi yok</h3><p>Oluşan işlemler ve sağlayıcıdan gelen sonuçlar burada görünür.</p></div>:<div className="table-scroll"><table className="billing-table"><thead><tr><th>İşlem</th>{platform&&<th>İşletme</th>}<th>Tarih</th><th>Tutar</th><th>Durum</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td title={o.id}>{o.id.slice(0,12)}…{o.test_mode===1&&<small className="billing-test">Test işlemi</small>}</td>{platform&&<td>{o.business_name}</td>}<td>{dates(o.created_at)}</td><td>{money(o.amount)}</td><td><span className={'billing-state '+(o.status==='paid'?'billing-paid':'')}>{statuses[o.status]||o.status}</span></td></tr>)}</tbody></table></div>}<p className="billing-footnote">Bu liste ödeme kaydıdır; mali belge yerine geçmez. İade ve banka mutabakatının yetkili satıcı tarafından sağlayıcı panelinde doğrulanması gerekir.</p></section>}
function BusinessBilling(){
 const {data:session}=useSession();const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[profile,setProfile]=useState({name:'',email:'',phone:'',address:''});
 const requestedPlan=typeof location==='undefined'?null:new URLSearchParams(location.search).get('plan');
 const initialPlan=['normal','pro','plus'].includes(requestedPlan||'')?requestedPlan:null;
 async function load(id?:string){setError('');try{const d=await api('billing'+(id?'?tenant='+encodeURIComponent(id):''));setData(d);setProfile(d.profile?{name:d.profile.name,email:d.profile.email,phone:d.profile.phone,address:d.profile.address}:{name:session?.profile?.name||'',email:session?.user?.email||'',phone:'',address:''})}catch(e:any){setError(e.message)}}
 useEffect(()=>{load(new URLSearchParams(location.search).get('tenant')||undefined)},[]);
 async function saveProfile(){await api('billing-profile',{tenant_id:data.business.id,...profile});}
 if(!data)return error?<p className="error-message">{error}</p>:<div className="loading-row"><Busy/>Aboneliğiniz yükleniyor…</div>;
 if(!data.business)return <section className="panel"><h1>Önce işletmenizi oluşturun.</h1><a className="button primary" href="/kurulum">İşletme oluştur</a></section>;
 return <><div className="billing-heading"><div><span className="eyebrow">ABONELİK VE ÖDEMELER</span><h1>Planınız, kontrolünüzde.</h1><p>{data.business.name} · Kartınız ödeme kuruluşunda yönetilir.</p></div><Pick label="İşletme seç" value={data.business.id} onChange={load} options={data.businesses.map((b:any)=>({value:b.id,label:b.name}))}/></div>
 {new URLSearchParams(location.search).get('onboarding')==='1'&&<p className="notice" role="status">İşletmeniz oluşturuldu. Seçtiğiniz paketi güvenli ödeme sağlayıcısında tamamlayabilirsiniz.</p>}
 <RecurringPlans key={data.business.id} tenantId={data.business.id} beforeCheckout={saveProfile} initialPlan={initialPlan||data.business.selected_plan}/>
 <section className="panel margin-top"><h2>Fatura iletişim bilgileri</h2><p className="muted">Abonelik başlatmadan önce tamamlayın. Kart bilgisi istenmez.</p><form className="form-stack margin-top" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await saveProfile();setMessage('Fatura iletişim bilgileri kaydedildi.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><div className="form-grid"><Field label="Ad / unvan"><Input required minLength={2} maxLength={100} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></Field><Field label="E-posta"><Input type="email" required value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></Field><Field label="Telefon"><Input type="tel" required value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></Field><Field label="Fatura adresi"><Input required minLength={10} maxLength={350} value={profile.address} onChange={e=>setProfile({...profile,address:e.target.value})}/></Field></div>{error&&<p className="error-message">{error}</p>}{message&&<p className="notice">{message}</p>}<button className="button" disabled={busy}>{busy?<Busy/>:<Check size={16}/>}Bilgileri kaydet</button></form></section>
 <section className="panel margin-top"><h2>Neta kredisi</h2><p className="muted">Referans kredileri pazarlama panelinizde görünür. Sağlayıcıda kredi mahsup akışı onaylanmadan kart yenileme tutarı azaltılmaz veya bakiyenizden abonelik tutarı düşülmez.</p><a className="text-button margin-top" href={'/panel/pazarlama?tenant='+data.business.id}>Kredi hareketlerim <ArrowRight size={16}/></a></section>
 <CampaignCheckout data={data} beforeCheckout={saveProfile}/>
 {data.orders.length>0&&<details className="legacy-billing"><summary>Önceki tek seferlik PayTR işlemleri</summary><History orders={data.orders}/></details>}</>;
}
function CampaignCheckout({data,beforeCheckout}:{data:any;beforeCheckout:()=>Promise<void>}){
 const [code,setCode]=useState(''),[quote,setQuote]=useState<any>(null),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function apply(){setBusy(true);setError('');try{const result=await api('campaign-preview?tenant='+encodeURIComponent(data.business.id)+'&plan='+encodeURIComponent(data.business.selected_plan)+'&code='+encodeURIComponent(code));setQuote(result);setCode(result.code)}catch(e:any){setQuote(null);setError(e.message)}finally{setBusy(false)}}
 async function checkout(){setBusy(true);setError('');try{await beforeCheckout();const result=await api('checkout',{tenant_id:data.business.id,idempotency_key:crypto.randomUUID(),terms_accepted:true,campaign_code:quote.code});if(!result.checkout_url?.startsWith('https://www.paytr.com/odeme/guvenli/'))throw new Error('Güvenli ödeme bağlantısı doğrulanamadı.');location.assign(result.checkout_url)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel margin-top campaign-payment-card"><div><span className="eyebrow">NETA ÖZEL İNDİRİM</span><h2>Kampanya kodunuz var mı?</h2><p className="muted">Kod ve paket uygunluğu sunucuda doğrulanır; ödeme tutarı tarayıcıdan alınmaz.</p></div><div className="campaign-code-row"><Input aria-label="İndirim kodu" autoComplete="off" maxLength={32} placeholder="Örn. NETA500" value={code} onChange={e=>{setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,''));setQuote(null)}}/><button className="button" type="button" disabled={busy||code.length<3} onClick={apply}>{busy?<Busy/>:'Uygula'}</button></div>{quote&&<div className="campaign-price-lines" role="status"><div><span>Normal paket fiyatı</span><b>{money(quote.original_amount)}</b></div><div className="campaign-discount"><span>{quote.campaign_name}</span><b>-{money(quote.discount_amount)}</b></div><div className="campaign-final"><span>Bugün ödenecek</span><b>{money(quote.final_amount)}</b></div><p className="campaign-note">{new Date(quote.ends_at).toLocaleDateString('tr-TR')} tarihine kadar geçerli · {quote.first_payment_only?'yalnızca ilk ödeme':quote.recurring_enabled?'yenilemeler dahil':'tek ödeme'}.</p><p className="campaign-note">{quote.provider_note}</p>{quote.checkout_supported&&<label className="check-row"><Checkbox checked={accepted} onCheckedChange={value=>setAccepted(value===true)}/><span>İndirimli tutarı ve abonelik koşullarını onaylıyorum.</span></label>}<button className="button primary full" type="button" disabled={busy||!accepted||!quote.checkout_supported} onClick={checkout}>{busy?<Busy/>:<CreditCard size={17}/>}İndirimli ödemeye geç</button></div>}{error&&<p className="error-message" role="alert">{error}</p>}{!data.checkout_available&&<p className="notice">PayTR mağaza bağlantısı satışa açılınca indirimli tahsilat butonu etkinleşir.</p>}</section>
}
function PlatformBilling(){
 const {data:session}=useSession();const [data,setData]=useState<any>(null),[form,setForm]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const reload=useCallback(async()=>{const d=await api('platform-billing');setData(d);return d},[]);
 useEffect(()=>{reload().then(d=>setForm({...d.settings,price:d.settings.amount?String(d.settings.amount/100):'',active:!!d.settings.active})).catch(e=>setError(e.message))},[reload]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const amount=Math.round(Number(form.price)*100);await api('platform-billing',{...form,amount});await reload();setMessage('Plan ve satıcı bilgileri kaydedildi. Geçmiş işlemlerin fiyatı değişmedi.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!session?.isAdmin)return <section className="panel account-gate"><ShieldCheck size={30}/><h1>Platform yöneticisi alanı</h1><p>Bu alan yalnızca Neta Randevu yöneticisine açıktır.</p><a className="button" href="/abonelik">İşletmemin aboneliği</a></section>;
 if(!data||!form)return error?<p className="error-message">{error}</p>:<div className="loading-row"><Busy/>Tahsilatlar hazırlanıyor…</div>;
 const c=data.connection;
 return <><div className="billing-heading"><div><span className="eyebrow">NETA RANDEVU · PLATFORM YÖNETİMİ</span><h1>Tahsilatın kontrolü sizde.</h1><p>İşletme aboneliklerini ve ödeme bağlantısını tek yerden izleyin.</p></div><a className="button" href="/admin">İşletmeleri yönet<ArrowRight size={16}/></a></div>{error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 <div className="billing-stats"><article className="panel"><span>Tahsil edilen brüt tutar</span><strong>{money(data.totals.paid_amount)}</strong><small>{data.totals.paid_count} doğrulanmış gerçek ödeme</small></article><article className="panel"><span>Doğrulama bekleyen</span><strong>{data.totals.pending_count}</strong><small>Test işlemleri dahil değil</small></article><article className="panel"><span>Bankaya aktarılan</span><strong className="billing-no-value">Doğrulama gerekli</strong><small>PayTR banka aktarımı verisi bağlı değil</small></article></div>
 <PlatformRecurring/><div className="billing-grid"><section className="panel"><h2>Ödeme bağlantısı</h2><div className="billing-check"><ShieldCheck size={20}/><div><strong>{c.credentials?'Sağlayıcı bilgileri tanımlı':'PayTR henüz bağlı değil'}</strong><small>Gizli anahtarlar yalnızca sunucunun korumalı ayarlarında tutulur.</small></div></div><div className="billing-check"><CreditCard size={20}/><div><strong>{c.test_mode?'Test modu':'Gerçek ödeme modu'}</strong><small>{c.test_mode?'Test işlemleri ciroya ve abonelik süresine eklenmez.':'Yalnızca imzası ve tutarı doğrulanmış bildirimler aboneliği uzatır.'}</small></div></div><div className="billing-check"><Store size={20}/><div><strong>{c.public_site?'Dış erişim yapılandırılmış':'Dış erişim kurulumu bekleniyor'}</strong><small>İşletmelerin ve ödeme sağlayıcısının siteye erişebilmesi gerekir.</small></div></div><div className="billing-check"><LockKeyhole size={20}/><div><strong>{data.auth.google?'Google giriş bağlantısı tanımlı':'Google girişi henüz bağlı değil'}</strong><small>Sağlayıcı ayarları tamamlanmadan Google girişi başlatılmaz.</small></div></div><div className="billing-check"><Landmark size={20}/><div><strong>Alıcı banka hesabı</strong><small>{c.bank_label}. Hesap doğrulaması ve değişiklikleri yetkili satıcının PayTR hesabında yönetilir.</small></div></div><div className="billing-flow"><span>İşletmenin ödemesi</span><ArrowRight size={16}/><span>PayTR tahsilatı</span><ArrowRight size={16}/><span>Doğrulanmış satıcı hesabı</span></div><p className="helper">Banka aktarım günü, kesintiler ve net tutar sağlayıcı sözleşmesine bağlıdır. Yukarıdaki brüt tahsilat, banka bakiyesi değildir. İade ve mutabakat PayTR panelinden yönetilir.</p><a className="text-button" href="https://www.paytr.com" target="_blank" rel="noopener noreferrer">PayTR web sitesi<ExternalLink size={15}/></a></section>
 <section className="panel"><h2>Abonelik planı</h2><p className="helper">Fiyatı siz belirlersiniz. Satışa açılmadan önce plan taslak olarak kalır.</p><form className="form-stack" onSubmit={save}><Field label="30 günlük toplam fiyat (TL)"><Input type="number" min="1" max="1000000" step="0.01" required placeholder="Henüz belirlenmedi" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></Field><Field label="Satıcı unvanı"><Input required minLength={2} maxLength={150} value={form.seller_name} onChange={e=>setForm({...form,seller_name:e.target.value})}/></Field><Field label="Destek e-postası"><Input required type="email" maxLength={254} value={form.support_email} onChange={e=>setForm({...form,support_email:e.target.value})}/></Field><Field label="Satıcı adresi"><textarea className="billing-address" required minLength={10} maxLength={350} value={form.seller_address} onChange={e=>setForm({...form,seller_address:e.target.value})}/></Field><Field label="Satış, iptal ve iade koşulları bağlantısı"><Input required type="url" placeholder="https://…" maxLength={500} value={form.terms_url} onChange={e=>setForm({...form,terms_url:e.target.value})}/></Field><label className="check-row"><Checkbox checked={form.active} disabled={!c.credentials||!c.public_site||!c.origin} onCheckedChange={v=>setForm({...form,active:v===true})}/><span>Planı satışa aç</span></label>{(!c.credentials||!c.public_site||!c.origin)&&<p className="helper">Ödeme bağlantısı ve dış erişim tamamlanınca satış açılabilir.</p>}<button className="button primary full" disabled={busy}>{busy?<Busy/>:<Check size={16}/>}Planı kaydet</button></form></section></div><div className="billing-toolbar"><button className="button" onClick={()=>reload().catch(e=>setError(e.message))}><RefreshCw size={16}/>İşlemleri yenile</button><span className="helper">Abonelik süresi bulunan {data.subscriptions.length} işletme</span></div><History orders={data.orders} platform/></>;
}
