'use client';
import {useState,useEffect} from 'react';
import {CalendarDays,Check,UserRound,Clock,Scissors,ShieldCheck,UserPlus,Trash2,ArrowRight} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {toast} from 'sonner';
import {api,Field,Pick,Busy,Blank,Confirm} from './common';
import {PublicShell} from './public';
import {AccountGate} from './session';
import {today,time,money,STATUS} from '@/lib/types';

export function TeamAccessPanel({w}:any){
 const [rows,setRows]=useState<any[]>([]),[staff,setStaff]=useState(w.staff[0]?.id||''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[removing,setRemoving]=useState('');
 async function refresh(){try{setRows((await api('team-access?tenant='+w.business.id)).members);setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(!w.preview)refresh()},[w.business.id]);
 if(w.preview)return null;
 return <section className="panel team-access margin-top"><div className="section-heading"><h2><ShieldCheck size={20}/>Personelin kendi ekranı</h2><a className="text-button" href="/ekibim">Ekip ekranı <ArrowRight size={15}/></a></div><p className="muted">Personeliniz önce Randevu üyeliğini tamamlasın. Hesabını bağlayınca yalnızca kendi randevularını ve işlem bilgilerini görür; işletme raporlarına erişemez.</p><form className="team-access-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('team-access',{tenant_id:w.business.id,staff_id:staff,email});setEmail('');await refresh();toast.success('Personel erişimi tanımlandı.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><Field label="Personel"><Pick label="Personel hesabı" value={staff} onChange={setStaff} options={w.staff.map((s:any)=>({value:s.id,label:s.name}))}/></Field><Field label="Üyelik e-postası"><Input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="personel@ornek.com"/></Field><button className="button" disabled={busy||!staff}>{busy?<Busy/>:<UserPlus size={17}/>}Hesabı bağla</button></form>{error&&<p className="error-message">{error}</p>}{rows.filter(r=>!r.disabled).map(r=><div className="list-row" key={r.user_id}><div><strong>{w.staff.find((s:any)=>s.id===r.staff_id)?.name}</strong><small>{r.email} · Sınırlı personel erişimi</small></div><button className="icon-button" aria-label={r.name+' erişimini kaldır'} onClick={()=>setRemoving(r.staff_id)}><Trash2 size={17}/></button></div>)}<Confirm open={!!removing} onClose={()=>setRemoving('')} title="Personelin erişimi kapatılsın mı?" description="Personel kaydı ve randevuları korunur. Bağlı hesap bu işletmenin iş listesine erişemez." onConfirm={async()=>{try{await api('team-access',{tenant_id:w.business.id,staff_id:removing,action:'remove'});setRemoving('');refresh()}catch(e:any){toast.error(e.message)}}}/></section>;
}
export default function TeamPage(){return <PublicShell><main className="member-page"><AccountGate returnTo="/ekibim"><TeamDesk/></AccountGate></main></PublicShell>}
function TeamDesk(){
 const [data,setData]=useState<any>(null),[date,setDate]=useState(today()),[tenant,setTenant]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[noShow,setNoShow]=useState<any>(null);
 async function refresh(){try{setData(await api('team-jobs?date='+date+'&tenant='+tenant));setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{refresh()},[date,tenant]);
 async function finish(a:any,status:string){setBusy(a.id);try{await api('team-jobs',{tenant_id:data.business.id,id:a.id,status});setNoShow(null);await refresh();toast.success('İşlem sonucu kaydedildi.')}catch(e:any){toast.error(e.message)}finally{setBusy('')}}
 return <><div className="member-heading"><div><span className="eyebrow">EKİP ALANINIZ</span><h1>Bugün, sizin ellerinizde.</h1><p>{data?.business?data.business.name+' · '+data.business.staff_name:'Size atanan randevular ve yapılacak işlemler.'}</p></div><div className="button-group">{data?.businesses?.length>1&&<Pick label="Çalıştığınız işletme" value={tenant||data.business.id} onChange={setTenant} options={data.businesses.map((b:any)=>({value:b.id,label:b.name}))}/>}<Input aria-label="İş günü" type="date" value={date} onChange={e=>setDate(e.target.value)} className="date-input"/></div></div>{error?<p className="error-message">{error}</p>:!data?<div className="loading-row"><Busy/>İş listeniz hazırlanıyor…</div>:!data.business?<section className="panel"><Blank title="Henüz bağlı bir işletmeniz yok" description="İşletme sahibi, Ekip bölümünden üyelik e-postanızı personel kaydınıza bağladığında iş listeniz burada açılır."/></section>:!data.appointments.length?<section className="panel"><Blank title="Bu gün için atanmış randevu yok" description="Başka bir tarih seçebilirsiniz."/></section>:<div className="team-job-grid">{data.appointments.map((a:any)=>{const ended=new Date(a.date+'T'+time(a.minute)+':00+03:00').getTime()+a.duration*60000<=Date.now();return <article className="panel team-job" key={a.id}><div className="section-heading"><strong className="team-job-time">{time(a.minute)} <span>– {time(a.minute+a.duration)}</span></strong><span className={'badge '+a.status}>{STATUS[a.status]}</span></div><div className="team-job-customer"><UserRound size={19}/><strong>{a.customer_name}</strong><span>{a.customer_phone}</span></div><div className="team-job-service"><Scissors size={23}/><div><h2>{a.service_name}</h2><p>{a.duration} dakika · {money(a.price)}</p></div></div>{a.service_description&&<p className="service-description">{a.service_description}</p>}{a.customer_note&&<div className="customer-note"><strong>Müşteri tercihi</strong><p>{a.customer_note}</p></div>}{a.early_from!=null&&<small className="early-tag"><Clock size={14}/>{time(a.early_from)} itibarıyla erken gelebilir</small>}{a.status==='confirmed'&&<div className="team-job-footer"><button className="button primary" disabled={!ended||!!busy} onClick={()=>finish(a,'completed')}>{busy===a.id?<Busy/>:<Check size={16}/>}İşlem tamamlandı</button><button className="text-button danger" disabled={!ended||!!busy} onClick={()=>setNoShow(a)}>Gelmedi</button>{!ended&&<small>Sonuç, planlanan bitişten sonra işaretlenebilir.</small>}</div>}</article>})}</div>}<Confirm open={!!noShow} onClose={()=>setNoShow(null)} title="Müşteri gelmedi mi?" description="Bu randevu gelmedi olarak işaretlenecek ve tamamlanan işlem gelirine eklenmeyecek." onConfirm={()=>noShow&&finish(noShow,'no_show')}/></>;
}
